select * from doctortable; 
select * from PresTable    ;
select * from staff_table ;
select * from menutable
update from PresTable set c_id = 'ss0000003' where c_id != 'ss';
select *   from logtable;
select * from appointment_table;
select * from PatientTable where c_id =' ss0000003'
select * from menu_tree
delete from  menu_tree
update staff_table set r_id = '2' where r_id != '1' and  r_id != '003'
select * from    (select c.*,c.c_id c  from card_event  c left join card_msg  p on c.c_id = p.c_id ) o left join card_msg  w on o.c= w.c_id  

select * from staff_table where s_keshi = (select d_id from depttable where d_name = '外科');

SELECT TO_CHAR(T.doc_date,'YYYY') YEAR,TO_CHAR(T.doc_date,'IW') TIME,COUNT(*) COUNT
FROM doctortable T;
select * from doctortable where to_char(to_date(doc_date,'yyyy-mm-dd hh24:mi:ss'),'iw')=to_char(sysdate,'iw')s

update  MENU_TREE  set m_state = '禁用' where l_mid  = '42' and M_state ='启用';

SET DEFINE OFF
INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('1', '', '', '#', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('2', '卡片业务', '', '1', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('3', '卡片管理', '', '1', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('4', '系统管理', '', '1', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('5', '统计查询', '', '1', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('6', '日常事务', '', '1', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('7', '卡入库', 'CardInServlet?action=addCardManage&currentPage=1', '3', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('8', '卡查询', 'ModifyCardServlet?action=modify&currentPage=1', '3', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('9', '领卡审批', 'ExamineApplyServlet?action=enter_exam&currentPage=1', '3', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('10', '卡注销', 'CancleCardServlet?action=cancle_Main&currentPage=1', '3', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('11', '领卡', 'Collar_CardServlet?action=enter_apply&currentPage=1', '2', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('12', '售卡', 'brower/charge_net/applycard/sell_Card.jsp', '2', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('13', '换卡', 'brower/charge_net/applycard/changeCard.jsp', '2', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('14', '退卡', 'brower/charge_net/applycard/retreatCard.jsp', '2', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('15', '处方退费', 'brower/charge_net/manageCard/permissionmanage.jsp', '6', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('16', '人员管理', 'ManageServlet?action=staffManage', '4', '启用');

update  MENUTABLE set m_url ='brower/charge_net/welcome.jsp' where m_id =  '21'
update  MENUTABLE set m_url ='SearchServlet?action=card_search&currentPage=1' where m_id =  '22'
update  MENUTABLE set m_url ='ModifyCardServlet?action=modify&currentPage=1' where m_id =  '8'
INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('18', '菜单管理', '', '4', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('19', '医生排班', 'Doctor_Servlet?action=enter_doct&current_id=1', '4', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('20', '日志查看', 'LogServlet?action=enter_log&current_id=1&currentPage=1', '4', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('21', '参数管理', '', '4', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('22', '领卡查询', 'SearchServlet?action=card_search&currentPage=1', '5', '启用');

INSERT INTO MENUTABLE (M_ID, M_NAME, M_URL, L_MID, M_STATE) 
VALUES ('23', '工作量统计', 'SearchServlet?action=works&currentPage=1', '5', '启用');









--------------------------------------------------------
--  DDL for Table TB_CARD_BUSINESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_CARD_BUSINESS" 
   (	"B_TIME" VARCHAR2(20 BYTE), 
	"B_THING" VARCHAR2(20 BYTE), 
	"B_RMB" VARCHAR2(20 BYTE), 
	"B_EXECUTOR" VARCHAR2(20 BYTE), 
	"B_card" VARCHAR2(20 BYTE), 
	"B_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_CARD_BUSINESS"."B_TIME" IS '发生时间';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_BUSINESS"."B_THING" IS '发生事项';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_BUSINESS"."B_RMB" IS '发生金额';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_BUSINESS"."B_EXECUTOR" IS '执行人';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_BUSINESS"."B_card" IS '卡号（外）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_BUSINESS"."B_ID" IS '业务ID（主）';
--------------------------------------------------------
--  DDL for Index TB_CARD_BUSINESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_CARD_BUSINESS_PK" ON "SYSTEM"."TB_CARD_BUSINESS" ("B_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_CARD_BUSINESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_CARD_BUSINESS" MODIFY ("B_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_CARD_BUSINESS" ADD CONSTRAINT "TB_CARD_BUSINESS_PK" PRIMARY KEY ("B_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_CARD_INFORMATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_CARD_INFORMATION" 
   (	"INF_CARD" VARCHAR2(20 BYTE), 
	"INF_CARD_BALANCE" VARCHAR2(20 BYTE), 
	"INF_CARD_STATE" VARCHAR2(20 BYTE), 
	"INF_CARD_USER" VARCHAR2(20 BYTE), 
	"INF_CARD_RECIPIENT" VARCHAR2(20 BYTE), 
	"INF_RECIPIENT_TIME" VARCHAR2(20 BYTE), 
	"INF_CARD_MARKET" VARCHAR2(20 BYTE), 
	"INF_MARKET_TIME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_CARD_INFORMATION"."INF_CARD" IS '卡号（主）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_INFORMATION"."INF_CARD_BALANCE" IS '卡余额';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_INFORMATION"."INF_CARD_STATE" IS '卡状态';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_INFORMATION"."INF_CARD_USER" IS '就诊人';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_INFORMATION"."INF_CARD_RECIPIENT" IS '领用人';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_INFORMATION"."INF_RECIPIENT_TIME" IS '领用时间';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_INFORMATION"."INF_CARD_MARKET" IS '售卡人';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_INFORMATION"."INF_MARKET_TIME" IS '售卡时间';
--------------------------------------------------------
--  DDL for Index TB_CARD_INFORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_CARD_INFORMATION_PK" ON "SYSTEM"."TB_CARD_INFORMATION" ("INF_CARD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_CARD_INFORMATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_CARD_INFORMATION" MODIFY ("INF_CARD" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_CARD_INFORMATION" ADD CONSTRAINT "TB_CARD_INFORMATION_PK" PRIMARY KEY ("INF_CARD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_CARD_REQUEST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_CARD_REQUEST" 
   (	"REQ_TIME" VARCHAR2(20 BYTE), 
	"REQ_NUMBER" VARCHAR2(20 BYTE), 
	"REQ_NAME" VARCHAR2(20 BYTE), 
	"REQ_AUDIT_STATE " VARCHAR2(20 BYTE), 
	"REQ_AUDIT_PEOPLE" VARCHAR2(20 BYTE), 
	"REQ_AUDIT_TIME " VARCHAR2(20 BYTE), 
	"REQ_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_CARD_REQUEST"."REQ_TIME" IS '申请时间';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_REQUEST"."REQ_NUMBER" IS '申请卡数量';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_REQUEST"."REQ_NAME" IS '申请人';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_REQUEST"."REQ_AUDIT_STATE " IS '审核状态';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_REQUEST"."REQ_AUDIT_PEOPLE" IS '审核人';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_REQUEST"."REQ_AUDIT_TIME " IS '审核时间';
 
   COMMENT ON COLUMN "SYSTEM"."TB_CARD_REQUEST"."REQ_ID" IS '申请ID(主）';
--------------------------------------------------------
--  DDL for Index TB_CARD_REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_CARD_REQUEST_PK" ON "SYSTEM"."TB_CARD_REQUEST" ("REQ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_CARD_REQUEST
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_CARD_REQUEST" MODIFY ("REQ_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_CARD_REQUEST" MODIFY ("REQ_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_CARD_REQUEST" ADD CONSTRAINT "TB_CARD_REQUEST_PK" PRIMARY KEY ("REQ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_LOG
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_LOG" 
   (	"L_ID" NUMBER, 
	"L_NAME" VARCHAR2(20 BYTE), 
	"L_TIME" VARCHAR2(20 BYTE), 
	"L_THING" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_LOG"."L_ID" IS '日志ID（主）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_LOG"."L_NAME" IS '操作人';
 
   COMMENT ON COLUMN "SYSTEM"."TB_LOG"."L_TIME" IS '操作时间';
 
   COMMENT ON COLUMN "SYSTEM"."TB_LOG"."L_THING" IS '操作事项';
--------------------------------------------------------
--  DDL for Index TB_LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_LOG_PK" ON "SYSTEM"."TB_LOG" ("L_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_LOG
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_LOG" MODIFY ("L_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_LOG" ADD CONSTRAINT "TB_LOG_PK" PRIMARY KEY ("L_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_MENU
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_MENU" 
   (	"M_ID" NUMBER, 
	"M_NAME" VARCHAR2(20 BYTE), 
	"M_URL" VARCHAR2(20 BYTE), 
	"M_UP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_MENU"."M_ID" IS '菜单ID（主）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_MENU"."M_NAME" IS '菜单名称';
 
   COMMENT ON COLUMN "SYSTEM"."TB_MENU"."M_URL" IS 'URL';
 
   COMMENT ON COLUMN "SYSTEM"."TB_MENU"."M_UP" IS '上级菜单';
--------------------------------------------------------
--  DDL for Index TB_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_MENU_PK" ON "SYSTEM"."TB_MENU" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_MENU
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_MENU" MODIFY ("M_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_MENU" ADD CONSTRAINT "TB_MENU_PK" PRIMARY KEY ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_PARAMETER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_PARAMETER" 
   (	"PAR_ID" NUMBER, 
	"PAR_NAME" VARCHAR2(20 BYTE), 
	"PAR_TYPE" VARCHAR2(20 BYTE), 
	"PAR_NUM" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_PARAMETER"."PAR_ID" IS '参数ID（主）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PARAMETER"."PAR_NAME" IS '参数名称';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PARAMETER"."PAR_TYPE" IS '参数类型';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PARAMETER"."PAR_NUM" IS '参数值';
--------------------------------------------------------
--  DDL for Index TB_PARAMETER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_PARAMETER_PK" ON "SYSTEM"."TB_PARAMETER" ("PAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_PARAMETER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_PARAMETER" MODIFY ("PAR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_PARAMETER" ADD CONSTRAINT "TB_PARAMETER_PK" PRIMARY KEY ("PAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_PERMISSIONS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_PERMISSIONS" 
   (	"P_ID" NUMBER, 
	"P_NAME" VARCHAR2(20 BYTE), 
	"W_ROLE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_PERMISSIONS"."P_ID" IS '权限ID（主）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PERMISSIONS"."P_NAME" IS '权限名';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PERMISSIONS"."W_ROLE" IS '角色（外）';
--------------------------------------------------------
--  DDL for Index TB_PERMISSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_PERMISSIONS_PK" ON "SYSTEM"."TB_PERMISSIONS" ("P_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_PERMISSIONS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_PERMISSIONS" MODIFY ("P_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_PERMISSIONS" ADD CONSTRAINT "TB_PERMISSIONS_PK" PRIMARY KEY ("P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_PRESCRIPTION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_PRESCRIPTION" 
   (	"PRE_ID" NUMBER, 
	"PRE_NAME" VARCHAR2(20 BYTE), 
	"PRE_WAY" VARCHAR2(20 BYTE), 
	"PRE_NUMBER" VARCHAR2(20 BYTE), 
	"PRE_UNIT" VARCHAR2(20 BYTE), 
	"PRE_PRICE" VARCHAR2(20 BYTE), 
	"PRE_SUM" VARCHAR2(20 BYTE), 
	"U_CARD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_PRESCRIPTION"."PRE_ID" IS '处方ID（主）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PRESCRIPTION"."PRE_NAME" IS '药品名称';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PRESCRIPTION"."PRE_WAY" IS '服用方式';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PRESCRIPTION"."PRE_NUMBER" IS '数量';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PRESCRIPTION"."PRE_UNIT" IS '单位';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PRESCRIPTION"."PRE_PRICE" IS '单价';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PRESCRIPTION"."PRE_SUM" IS '小计';
 
   COMMENT ON COLUMN "SYSTEM"."TB_PRESCRIPTION"."U_CARD" IS '卡号（外）';
--------------------------------------------------------
--  DDL for Index TB_PRESCRIPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_PRESCRIPTION_PK" ON "SYSTEM"."TB_PRESCRIPTION" ("PRE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_PRESCRIPTION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_PRESCRIPTION" MODIFY ("PRE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_PRESCRIPTION" ADD CONSTRAINT "TB_PRESCRIPTION_PK" PRIMARY KEY ("PRE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_REGISTRATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_REGISTRATION" 
   (	"REG_ID" NUMBER, 
	"REG_TIME" VARCHAR2(20 BYTE), 
	"REG_SEETIME" VARCHAR2(20 BYTE), 
	"REG_DOCTOR" VARCHAR2(20 BYTE), 
	"REG_DEPARTMENT" VARCHAR2(20 BYTE), 
	"U_CARD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_REGISTRATION"."REG_ID" IS '预约ID(主）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_REGISTRATION"."REG_TIME" IS '预约时间';
 
   COMMENT ON COLUMN "SYSTEM"."TB_REGISTRATION"."REG_SEETIME" IS '预约就诊日期';
 
   COMMENT ON COLUMN "SYSTEM"."TB_REGISTRATION"."REG_DOCTOR" IS '预约医生';
 
   COMMENT ON COLUMN "SYSTEM"."TB_REGISTRATION"."REG_DEPARTMENT" IS '预约科室';
 
   COMMENT ON COLUMN "SYSTEM"."TB_REGISTRATION"."U_CARD" IS '用户卡号（外）';
--------------------------------------------------------
--  DDL for Index TB_REGISTRATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_REGISTRATION_PK" ON "SYSTEM"."TB_REGISTRATION" ("REG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_REGISTRATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_REGISTRATION" MODIFY ("REG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_REGISTRATION" ADD CONSTRAINT "TB_REGISTRATION_PK" PRIMARY KEY ("REG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_SCHEDULING
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_SCHEDULING" 
   (	"S_TIME" VARCHAR2(20 BYTE), 
	"W_NAME" VARCHAR2(20 BYTE), 
	"U_CARD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_SCHEDULING"."S_TIME" IS '时间（主）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_SCHEDULING"."W_NAME" IS '名字（外）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_SCHEDULING"."U_CARD" IS '用户（外）';
--------------------------------------------------------
--  DDL for Index TB_DOCTOR_SCHEDULING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_DOCTOR_SCHEDULING_PK" ON "SYSTEM"."TB_SCHEDULING" ("S_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_SCHEDULING
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_SCHEDULING" MODIFY ("S_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_SCHEDULING" ADD CONSTRAINT "TB_DOCTOR_SCHEDULING_PK" PRIMARY KEY ("S_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_USER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_USER" 
   (	"U_CARD" VARCHAR2(20 BYTE), 
	"U_NAME" VARCHAR2(20 BYTE), 
	"U_SEX" VARCHAR2(20 BYTE), 
	"U_AGE" VARCHAR2(20 BYTE), 
	"U_NATIVEPLACE" VARCHAR2(20 BYTE), 
	"U_IDCARD" VARCHAR2(20 BYTE), 
	"U_PHONE" VARCHAR2(20 BYTE), 
	"U_ADRESS" VARCHAR2(20 BYTE), 
	"U_BALANCE" VARCHAR2(20 BYTE), 
	"U_DEPOSIT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_CARD" IS '卡号（主)';
 
   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_NAME" IS '名字';
 
   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_SEX" IS '性别';
 
   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_AGE" IS '年龄';
 
   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_NATIVEPLACE" IS '籍贯';
 
   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_IDCARD" IS '身份证';
 
   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_PHONE" IS '电话';
 
   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_ADRESS" IS '地址';
 
   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_BALANCE" IS '余额';
 
   COMMENT ON COLUMN "SYSTEM"."TB_USER"."U_DEPOSIT" IS '押金';
--------------------------------------------------------
--  DDL for Index TB_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_USER_PK" ON "SYSTEM"."TB_USER" ("U_CARD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_USER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_USER" MODIFY ("U_CARD" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_USER" ADD CONSTRAINT "TB_USER_PK" PRIMARY KEY ("U_CARD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Table TB_WORKER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TB_WORKER" 
   (	"W_NAME" VARCHAR2(20 BYTE), 
	"W_ROLE" VARCHAR2(20 BYTE), 
	"W_DEPARTMENT" VARCHAR2(20 BYTE), 
	"W_STATE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."TB_WORKER"."W_NAME" IS '人员姓名（主）';
 
   COMMENT ON COLUMN "SYSTEM"."TB_WORKER"."W_ROLE" IS '角色';
 
   COMMENT ON COLUMN "SYSTEM"."TB_WORKER"."W_DEPARTMENT" IS '科室';
 
   COMMENT ON COLUMN "SYSTEM"."TB_WORKER"."W_STATE" IS '状态';
--------------------------------------------------------
--  DDL for Index TB_WORKER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_WORKER_PK" ON "SYSTEM"."TB_WORKER" ("W_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TB_WORKER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TB_WORKER" MODIFY ("W_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."TB_WORKER" ADD CONSTRAINT "TB_WORKER_PK" PRIMARY KEY ("W_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
